config/routes.rb
NonScaffoldedRails::Application.routes.draw do

  root :to => 'info#index'

  match 'about_us' => 'info#about', :as => 'about'

  match 'contact_us' => 'info#contact', :as => 'contact'

  match 'posts' => 'posts#index', :as => 'posts', :via => :get

  match 'posts/new' => 'posts#new', :as => 'new_post', :via => :get

  match 'posts/:id' => 'posts#show', :as => 'post', :via => :get

  match 'posts/:id' => 'posts#destroy', :as =>'destroy_post', :via => :delete

  match 'posts' => 'posts#create', :as => 'create_post', :via => :post

  match 'posts/:id/edit' => 'posts#edit', :as => 'edit_post', :via => :get

  match 'posts/:id' => 'posts#update', :as => 'update_post', :via => :put 

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title

  validates :title, :content, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
	def index
	end

	def about
	end

	def contact
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
	#Route defined for this index action
	# the URL being /posts
  def index
  	@posts = Post.order('id DESC')
  end

  def show
  	@post = Post.find(params[:id])
  end #Auto load the app/views/posts/show.html.erb

  def new
  	@post = Post.new
  end #Load the app/views/posts/new.html.erb

  def create
  	#Create a new post object with the data the user 
  	#submitted from the new view form.
  	@post = Post.new(params[:post])

  	if (@post.save)
  		redirect_to :action => :index
  	else
  		render :action => :new
  	end
  end # Only loads a view on error. Otherwise redirects

  def destroy
  	@post = Post.find(params[:id])
  	@post.destroy
  	redirect_to :action => :index
  end #This action has no associated view. It always redirects.
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/info/about.html.erb
<h2>Hello there! About page</h2>

<p>Stare at ceiling give attitude. Flop over behind the couch rub face on everything for lick butt. Intrigued by the shower intrigued by the shower climb leg for chew foot nap all day. Claw drapes. Cat snacks intently sniff hand chase imaginary bugs. Shake treat bag play time find something else more interesting chew iPad power cord but chase imaginary bugs but find something else more interesting. Stretch behind the couch or cat snacks for need to chase tail.</p>

<p>Hide when guests come over hide when guests come over. Rub face on everything. Leave dead animals as gifts nap all day so flop over but throwup on your pillow but swat at dog. Cat snacks mark territory, so sweet beast or sleep on keyboard for inspect anything brought into the house and why must they do that. Cat snacks hide when guests come over chew iPad power cord use lap as chair for rub face on everything, and run in circles for sweet beast. Stand in front of the computer screen inspect anything brought into the house behind the couch. Missing until dinner time burrow under covers, and flop over yet chase mice or shake treat bag flop over or shake treat bag.</p>

<p>Rub face on everything chew iPad power cord so inspect anything brought into the house so need to chase tail intently stare at the same spot yet throwup on your pillow rub face on everything. Lick butt chew foot, chew foot. Sweet beast intrigued by the shower or all of a sudden go crazy but play time intently sniff hand. Chase mice under the bed play time use lap as chair rub face on everything. Under the bed run in circles so missing until dinner time. Lick butt hopped up on goofballs yet attack feet claw drapes need to chase tail. Need to chase tail missing until dinner time or throwup on your pillow so chase mice swat at dog so play time for lick butt. Destroy couch intently sniff hand so attack feet use lap as chair. Chew foot play time but play time.</p>

app/views/info/contact.html.erb
<h2>Hello there! Contact page</h2>

<p>Stare at ceiling give attitude. Flop over behind the couch rub face on everything for lick butt. Intrigued by the shower intrigued by the shower climb leg for chew foot nap all day. Claw drapes. Cat snacks intently sniff hand chase imaginary bugs. Shake treat bag play time find something else more interesting chew iPad power cord but chase imaginary bugs but find something else more interesting. Stretch behind the couch or cat snacks for need to chase tail.</p>

<p>Hide when guests come over hide when guests come over. Rub face on everything. Leave dead animals as gifts nap all day so flop over but throwup on your pillow but swat at dog. Cat snacks mark territory, so sweet beast or sleep on keyboard for inspect anything brought into the house and why must they do that. Cat snacks hide when guests come over chew iPad power cord use lap as chair for rub face on everything, and run in circles for sweet beast. Stand in front of the computer screen inspect anything brought into the house behind the couch. Missing until dinner time burrow under covers, and flop over yet chase mice or shake treat bag flop over or shake treat bag.</p>

<p>Rub face on everything chew iPad power cord so inspect anything brought into the house so need to chase tail intently stare at the same spot yet throwup on your pillow rub face on everything. Lick butt chew foot, chew foot. Sweet beast intrigued by the shower or all of a sudden go crazy but play time intently sniff hand. Chase mice under the bed play time use lap as chair rub face on everything. Under the bed run in circles so missing until dinner time. Lick butt hopped up on goofballs yet attack feet claw drapes need to chase tail. Need to chase tail missing until dinner time or throwup on your pillow so chase mice swat at dog so play time for lick butt. Destroy couch intently sniff hand so attack feet use lap as chair. Chew foot play time but play time.</p>

app/views/info/index.html.erb
<h2>Hello there! Home page</h2>

<p>Stare at ceiling give attitude. Flop over behind the couch rub face on everything for lick butt. Intrigued by the shower intrigued by the shower climb leg for chew foot nap all day. Claw drapes. Cat snacks intently sniff hand chase imaginary bugs. Shake treat bag play time find something else more interesting chew iPad power cord but chase imaginary bugs but find something else more interesting. Stretch behind the couch or cat snacks for need to chase tail.</p>

<p>Hide when guests come over hide when guests come over. Rub face on everything. Leave dead animals as gifts nap all day so flop over but throwup on your pillow but swat at dog. Cat snacks mark territory, so sweet beast or sleep on keyboard for inspect anything brought into the house and why must they do that. Cat snacks hide when guests come over chew iPad power cord use lap as chair for rub face on everything, and run in circles for sweet beast. Stand in front of the computer screen inspect anything brought into the house behind the couch. Missing until dinner time burrow under covers, and flop over yet chase mice or shake treat bag flop over or shake treat bag.</p>

<p>Rub face on everything chew iPad power cord so inspect anything brought into the house so need to chase tail intently stare at the same spot yet throwup on your pillow rub face on everything. Lick butt chew foot, chew foot. Sweet beast intrigued by the shower or all of a sudden go crazy but play time intently sniff hand. Chase mice under the bed play time use lap as chair rub face on everything. Under the bed run in circles so missing until dinner time. Lick butt hopped up on goofballs yet attack feet claw drapes need to chase tail. Need to chase tail missing until dinner time or throwup on your pillow so chase mice swat at dog so play time for lick butt. Destroy couch intently sniff hand so attack feet use lap as chair. Chew foot play time but play time.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NonScaffoldedRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<p>
		<%= image_tag 'rails.png' %>
	</p>

	<p>
		<ul>
			<li><%= link_to 'Home', root_path %></li>
			<li><%= link_to 'About', about_path %></li>
			<li><%= link_to 'Contact', contact_path %></li>
			<li><%= link_to 'Blog', posts_path %></li>
		</ul>
	</p>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>The Blog</h1>

<div id="blog">
	<% @posts.each do |post| %>
	<h3><%= link_to post.title, post %></h3>
	<p><%= post.content %></p>
	<p>Created at: <%= post.created_at %></p>
	<p><%= link_to 'Delete', post, :method => :delete, :data => { confirm: 'Are you sure?'} %></p>
	<hr />
	<% end %>

	<p>
		<%= link_to 'Create New Blog Post', new_post_path %>
	</p>
</div>

app/views/posts/new.html.erb
<h2>Create a New Post</h2>
<!--The f block param is known as a form builder.
	We use it to build the elements of our form. -->
<%= form_for @post do |f| %>
	<div>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</div>
	<div>
		<%= f.label :content %> <br />
		<%= f.text_area :content %>
	</div>
	<div>
		<%= f.submit 'Submit New Post' %>
	</div>
<% end %>

app/views/posts/show.html.erb
<h2>Company Blog</h2>
<h3><%= @post.title %></h3>
<p><%= @post.created_at %></p>
<p><%= @post.content %></p>